# permissions for end users to view subprocesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: subprocess-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: subprocess
    app.kubernetes.io/part-of: subprocess
    app.kubernetes.io/managed-by: kustomize
  name: subprocess-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - subprocesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - subprocesses/status
  verbs:
  - get
