apiVersion: webapp.my.domain/v1
kind: Subprocess
metadata:
  labels:
    app.kubernetes.io/name: subprocess
    app.kubernetes.io/instance: subprocess-sample
    app.kubernetes.io/part-of: subprocess
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: subprocess
  name: subprocess-sample
  finalizers:
    - batch.tutorial.kubebuilder.io/finalizer
spec:
  # TODO(user): Add fields here
  commands:
    - "jupyter-notebook --allow-root"
    - "sleep inf"
  foo: bar

